project:
  execute-dir: project
  output-dir: pages
  render:
    - index.qmd


date: now
date-format: "DD.MM.YYYY HH:mm:ss z"
published-title: "Sist oppdatert"

execute:
    echo: false
    warning: false
    daemon: false