apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: teamia
  name: ia-tjenester-metrikker-datafortelling
  namespace: teamia
spec:
  image: {{ image }}
  ttlSecondsAfterFinished: 340
  schedule: "*/15 * * * *"
  backoffLimit: 2
  envFrom:
    - secret: ia-tjenester-metrikker-datafortelling-secrets
    - optional: true
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
---
apiVersion: nais.io/v1
kind: Alert
metadata:
  name: ia-tjenester-metrikker-datafortelling
  namespace: teamia
  labels:
    team: teamia
    app: ia-tjenester-metrikker-datafortelling
spec:
  receivers:
    slack:
      channel: '#arbeidsgiver-teamia-alerts'
      prependText: '<!here> | '
  alerts:
    - alert: Naisjob feiler
      description: Naisjob ia-tjenester-metrikker-datafortelling feiler i namespace teamia
      expr: 'kube_job_failed{job_name=~"^ia-tjenester-metrikker-datafortelling.*", namespace="teamia"} > 0'
      for: 1m
      action: "Se logger på https://logs.adeo.no -> søk etter `pod:ia-tjenester-metrikker-datafortelling AND namespace:teamia`"
      severity: danger
