apiVersion: nais.io/v1
kind: Naisjob
metadata:
  annotations:
    nais.io/read-only-file-system: "false"
  name: team-ia-datafortellinger
  labels:
    team: teamia
  namespace: teamia
spec:
  image: {{ image }}
  resources:
    limits:
      memory: 8Gi
    requests:
      memory: 1Gi
  ttlSecondsAfterFinished: 340
  schedule: "0 8-16 * * 1-5"
  backoffLimit: 2
  gcp:
    bigQueryDatasets:
      - name: ia_tjenester_metrikker
        permission: READ
  envFrom:
    - secret: teamia-nada-secret # from Google Secret Manager
  env:
    - name: NADA_ENV
      value: data.nav.no
    - name: LEVERTE_IA_TJENESTER_QUARTO_ID
      value: 15c12bb7-30b0-4dc2-9ef0-afc72c2a03d8
    - name: KEY_METRICS_QUARTO_ID
      value: 2f6249ef-67bc-4fe6-bd35-502f2e739c4e
  accessPolicy:
    outbound:
      external:
        - host: data.nav.no