---
title: Leverte IA-tjenester
subtitle: Oversikt over digitale IA-tjenester i selvbetjente løsninger.
title-block-banner: true
title-block-banner-color: white
date: now
date-format: "DD.MM.YYYY HH:mm:ss z"
published-title: "Oppdatert"
author-title: "Eier"
author: Team IA
execute:
    echo: false
    warning: false
    daemon: false
format:
    html:
        toc: true
        toc-title: Indeks
        page-layout: full
        embed-resources: true
        theme: minty
        grid:
          body-width: 1000px
jupyter: python3
---
Statistikken på denne siden viser antall leverte digitale IA-tjenester.

En digital IA-tjeneste telles når en bruker har benyttet seg av innholdet i
tjenesten. Det er ikke tilstrekkelig at brukeren kun har besøkt forsiden.

Dataregistreringen startet mars 2021.

NB! Dette er ikke offisiell statistikk og må ikke deles utenfor NAV.

<div style="color: gray;">
Kildekoden finnes på [GitHub](https://github.com/navikt/ia-datafortelling).
</div>

```{python}
# Hindre caching-problematikk ved lokal kjøring
%load_ext autoreload
%autoreload 2

import sys
sys.path.append('..')

from data_prepping import prep_data
from common.data_fetching import query_data

PROJECT = "teamia-prod-df3d"
DATASET = "ia_tjenester_metrikker"
TABLE = "IA-tjenester-metrikker"

raw_data = query_data(PROJECT, DATASET, TABLE)
data = prep_data(raw_data)
```

# Unike virksomheter
```{python}
from plots import unike_virksomheter_bulletlist
unike_virksomheter_bulletlist(data)
```

```{python}
from plots import plot_unike_bedrifter
plot_unike_bedrifter(data)
```

## Kululativt historgram av unike virksomheter
```{python}
from plots import plot_antall_unike_virksomheter_kumulativt
plot_antall_unike_virksomheter_kumulativt(data)
```


# Leverte digitale IA-tjenester per tjeneste/applikasjon
```{python}
from plots import plot_tjenester_per_applikasjon
plot_tjenester_per_applikasjon(data)
```

### Siste 24 måneder
```{python}
from plots import tabell_antall_per_app_siste_24_mnd
tabell_antall_per_app_siste_24_mnd(data)
```

### Siste 30 dager
```{python}
from plots import  tabell_antall_per_app_siste_30_dager
tabell_antall_per_app_siste_30_dager(data)
```

# Informasjons- vs. interaksjonstjeneste i forebyggingsplan
```{python}
from plots import plot_informasjon_vs_interaksjon
plot_informasjon_vs_interaksjon(data)
```

# Fordeling antall ansatte
```{python}
from plots import plot_fordeling_antall_ansatte
plot_fordeling_antall_ansatte(data)
```

# Tilbakevendende brukere
Grafene viser antall og prosentandel av virksomheter som har fått levert digital
IA-tjeneste i gjeldende kvartal, og som samtidig fikk levert digital IA-tjeneste
kvartalet etter. Dette gir en indikasjon på hvor mange av virksomhetene som jobber
systematisk med IA.

```{python}
from plots import plot_tilbakevendende_brukere
plot_tilbakevendende_brukere(data)
```
